lifinance/customized-token-list

pol.json

Added $IXT on Polygon for marketing purposes

Added $IXT for marketing purposes

---

ava.json

Added $PTP Token on AVAX for marketing purposes

Added $PTP Token for marketing purposes

---

pol.json

Updated logo on $IXT

---

eth.json

Added $X2Y2 token on ETH for marketing purposes

Added $X2Y2 token for marketing purposes

---

eth.json

Added $CULT on ETH for marketing purposes

Added $CULT for marketing purposes

---

pol.json

Updated logo for $miMatic on POLYGON

Updated logo for $miMatic

---

pol.json

Added $CGS token

---

eth.json

Added $APE Token

---

opt.json

Added $OP token on Optimistic Ethereum

Added $OP token

---

pol.json

Adding $BOB for marketing purposes on Polygon

Adding $BOB for marketing purposes

---

eth.json

Adding $BOB

---

tokens/ETH.json
tokens/FUS.json

yes, they only have two decimals: https://etherscan.io/token/0x67C5870b4A41D4Ebef24d2456547A03F1f3e094B

feat: add GoodDollar

---

tokens/ARB.json
tokens/AVA.json
tokens/BSC.json
tokens/DAI.json
tokens/OPT.json
tokens/POL.json

Updated FRACTION Icon paths on GnosisChain and Polygon. 
Added FRACTION on Optimism, Arbitrum, Avalanche and BNBChain.

Updated FRACTION

---

tokens/POL.json

Adding Relay Token

---

tokens/ARB.json

Adding BOB

---

tokens/AVA.json

Adding BRZ

---

tokens/MOO.json

Ading xcRMRK

---

tokens/ARB.json

Adding sperax token on arbitrum

Adding sperax token

---

tokens/ARB.json

Adding Wombat Token

---

tokens/BSC.json

Adding Wombat Token on BSC

---

tokens/ETH.json

Update ETH with IPOR token.json

---

tokens/BSC.json

Update BSC with COP Token.json

Update BSC with COP Token.json

---

tokens/ETH.json

Update ETH token list with SquidGrow token

Update ETH token list with SquidGrow token

---

tokens/OPT.json

Update OPT with OPX token.json

---

tokens/BSC.json

Update BSC with SquidGrow token

Update BSC with SquidGrow token

---

tokens/FTM.json

Step 1 of this: https://lifi.atlassian.net/browse/LF-4675

feat: add axlUSDC

---

tokens/ARB.json

Update ARB with MOZ token

---

tokens/ARB.json

Update ARB with WOM token

---

tokens/ETH.json

Update ETH with WOM token

---

tokens/BSC.json

Update BSC with WOM token

---

tokens/BAS.json

Tokens highlighted here: https://lifi.atlassian.net/browse/LF-5057

added TOSHI - HZN - BALD for BAS

---

tokens/ETH.json
tokens/POL.json

https://etherscan.io/address/0x249ca82617ec3dfb2589c4c17ab7ec9765350a18
https://polygonscan.com/token/0xc708d6f2153933daa50b2d0758955be0a93a8fec

feat: add verse tokens

---

tokens/ETH.json

Update ETH with NXRA

---

tokens/POL.json

Update POL with NXRA

---

tokens/BSC.json

Update BSC with NXRA

---

tokens/AVA.json

Update AVA with NXRA

---

tokens/POL.json

Bonsai is a DN-404 token on Polygon for open actions across the Lens ecosystem.

Add BONSAI on Polygon

---

tokens/ARB.json
tokens/DAI.json
tokens/ETH.json
tokens/OPT.json
tokens/PZE.json

adding some popular memecoins images that are not on Jumper

feat: add some popular memecoins images

---

tokens/ETH.json

Requested by Zord4n:
https://etherscan.io/address/0x419d0d8bdd9af5e606ae2232ed285aff190e711b
https://coinmarketcap.com/currencies/funtoken/

feat: add FUN token on ETH

---

tokens/BAS.json
tokens/ETH.json

https://www.coingecko.com/en/coins/imgnai
Requested by Zord4n

feat: add ImageCoin token

---

tokens/SEI.json

feat: add fxs token on sei chain

---

denyTokens/OPT.json

I added a fake usdt token to the deny token lists.

fix: Update OPT.json

---

denyTokens/SOL.json

Add PyUSD token to SOL deny list until we are able to handle it gracefully.

Chore: Update SOL.json

---

tokens/BAS.json

Add token details for The Innovation Game (TIG) on Base

Add TIG token: Update BAS.json

---

tokens/SEI.json

Updated name for wETH + added wBTC details

Update SEI (update wETH, add wBTC).json

---

tokens/ETH.json
tokens/POL.json

- Added fluid token in ETH.json and POL.json

Add FLUID 

---

tokens/BSC.json

Add VANA token to BSC.json

---

tokens/BAS.json

Add VANA Token to BAS.json

---

tokens/ARB.json

Add VANA Token to ARB.json

---

tokens/OPT.json

Add VANA Token to OPT.json

---

tokens/POL.json

Add VANA Token to POL.json

---

.github/actions/install/action.yml
.github/workflows/lint.yml
.github/workflows/validate.yml
package.json
pnpm-lock.yaml
tokens/POL.json

chore: update pnpm to 9

---

tokens/ARB.json
tokens/AVA.json
tokens/BAS.json
tokens/BSC.json
tokens/DAI.json
tokens/ETH.json
tokens/POL.json

Add Backed tokens:
-- bCSPX
-- bCOIN, wbCOIN
-- bTSLA, wbTSLA
-- bNVDA, wbNVDA
-- bMSTR, wbMSTR

Add Backed tokens

---

denyTokens/BSC.json

https://lifi.atlassian.net/browse/LF-12439

chore: Deny CATX because it's 100% tax

---

tokens/ARB.json
tokens/BAS.json
tokens/BLS.json
tokens/BSC.json
tokens/ERA.json
tokens/ETH.json
tokens/FRA.json
tokens/LNA.json
tokens/MAM.json
tokens/MOD.json
tokens/OPT.json
tokens/SCL.json

- Added Ethena tokens so we can integrate the LiFi widget across the chains we support
- https://ethena.fi/

Add Ethena tokens

---

tokens/ETH.json

Hello @myz1237, 
requesting wPAW / Wrapped PAW. 
From: #114

Add wPAW (Wrapped PAW)

---

tokens/BAS.json

Updated logoURI to reflect brand change

feat: Update TIG logo on BAS

---

package.json
pnpm-lock.yaml
tokens/SWL.json

Added USDe on Swell according to Debank:

feat(SWL): add USDe

---

tokens/SOL.json

Add Ethena's tokens to the Solana chain so we can utilise within https://app.ethena.fi/

feat: add Ethena on Solana

---

denyTokens/SOL.json

We don't support Token-2022 tokens at the moment

feat(deny): add TIMI to denied tokens

---

tokens/BER.json

chore: Update BER.json

---

tokens/BAS.json

Cheers from https://plaza.finance :)

feat: add BondETH and LevETH on Base

---

tokens/SEI.json

feat: update SEI.json

---

tokens/POL.json

Change BRZ contract address to the address supported by Airlift

fix: update BRZ address

---

tokens/ETH.json

add stETH to ETH.json so we can fetch price from mainnet

feat: add stETH to ETH.json

---

tokens/OPT.json
tokens/SOE.json
tokens/SON.json
tokens/UNI.json

To make sure they are available on these chains I added them here. On Ethereum we have them already on all stages.

feat: add lido tokens

---

tokens/ETL.json

feat: add ETL tokens

---

package.json
pnpm-lock.yaml
tokens/ARB.json
tokens/BAS.json
tokens/BSC.json
tokens/CRO.json
tokens/POL.json
tokens/SOL.json

crow with knife (CAW) is a multichain token spanning 6 chains and bridged via Stargate v2 Hydra and LayerZero. This PR adds its token information for each of these chains. Information in all the links below will confirm the contract addresses in this PR.
Validation:
Website: https://www.crowwithknife.com/
CoinGecko: https://www.coingecko.com/en/coins/crow-with-knife
CoinMarketCap: https://coinmarketcap.com/currencies/crow-with-knife
DexScreener: https://dexscreener.com/watchlist/o9PAJYZXG4GkjwRXtgFx
X: https://x.com/crow_with_knife

feat: add CAW tokens

---

tokens/BSC.json

Add the IOST token to the BSC chain

feat: add iost token

---

tokens/CRO.json

KitCoin (KITTY) is a long established token on Cronos (1 year & 3 months). KitCoin has developed an NFT collection & also a DApp CroVegas.Fun listed on DappRadar, DefiLlama, Cronos Discover & Crypto.com's OnChain Wallet. This PR adds KitCoin's native token KITTY to CRO.json Please find links below for verification. Thank you
- Website: https://www.kitcoin.io/
- Cronoscan: https://cronoscan.com/token/0x4d7c922D6C12CfbF5BC85F56c9ccB1F61f49bf61
- DexScreener: https://dexscreener.com/cronos/0xdc1ff76d4737b2F54bbF42656FB998650b7A2b00
- GeckoTerminal: https://www.geckoterminal.com/cro/pools/0xdc1ff76d4737b2f54bbf42656fb998650b7a2b00
- X: https://x.com/kitcoinx
- MemesOnCronos: https://www.memesoncronos.com/tokens/kitcoin
- Dapp: https://www.crovegas.fun/
- DappRadar: …

feat: Add KITTY on Cronos

---

tokens/ETH.json

feat: add get-out-frog in the list

---

tokens/CRO.json
tokens/ETH.json

feat: Add CROTCH token on ETH and CRO

feat: Add CROTCH token on ETH and CRO

---

tokens/SOL.json

It should be 9, rather than 18 in terms of decimals

fix: correct decimals for SOL

---

tokens/XDC.json

feat: add USDB

---

tokens/SOL.json

Adds LION on SOL
Coingecko: https://www.coingecko.com/en/coins/loaded-lions
CoinmarketCap: https://coinmarketcap.com/currencies/loaded-lions/
Solscan: https://solscan.io/token/7kN5FQMD8ja4bzysEgc5FXmryKd6gCgjiWnhksjHCFb3

feat: add LION on SOL
